### ISSUE TITLE
Bug? "device_name" in influxDB is the same for all devices.

### ISSUE THREAD

**Issue by ngolf** [Tigge/openant#108]
I am using the built in influxdb command, and a config file.

The "device" tag value in influxdb is the same for all devices, particularly, it adopts the name of the last device in my config file.

E.g config:

`{
    "devices": [
        {
            "device": "FitnessEquipment",
            "id": 9384,
            "transmission_type": 5
        },

        {
            "device": "PowerMeter",
            "id": 35015,
            "transmission_type": 101
        },
        {
            "device": "BikeSpeedCadence",
            "id": 9384,
            "transmission_type": 1
        },
        {
            "device": "HeartRate",
            "id": 50967,
            "transmission_type": 193
        },
        {
            "device": "PowerMeter",
            "id": 9384,
            "transmission_type": 5
        }
    ]
}`

Output (note the HR data stored as power_meter_09384. If I put the HR sensor last in the list, then the all sensors would get  device = heart_rate_50967):
```
Device power_meter_09384 broadcast heart_rate data: HeartRateData(page_specific=3464960, beat_time=14.41796875, beat_count=21, heart_rate=51, operating_time=16777215, manufacturer_id_lsb=255, serial_number=65535, previous_heart_beat_time=13.2177734375, battery_percentage=255)
Writing: {'measurement': 'HeartRateData', 'tags': {'device': 'power_meter_09384', 'uuid': '4bd24577-9783-4e82-8cb9-4eaf7d699c12', 'host': 'pi5'}, 'time': 1724695493492374016, 'fields': {'page_specific': 3464960, 'beat_time': 14.41796875, 'beat_count': 21, 'heart_rate': 51, 'operating_time': 16777215, 'manufacturer_id_lsb': 255, 'serial_number': 65535, 'previous_heart_beat_time': 13.2177734375, 'battery_percentage': 255}}
Device power_meter_09384 broadcast standard_power data: PowerData(instantaneous_power=0, average_power=81, left_power=-1, right_power=-1, torque=3.44505033557047, angular_velocity=23.092251657330152, cadence=16)
Writing: {'measurement': 'PowerData', 'tags': {'device': 'power_meter_09384', 'uuid': '4bd24577-9783-4e82-8cb9-4eaf7d699c12', 'host': 'pi5'}, 'time': 1724695493926188032, 'fields': {'instantaneous_power': 0, 'average_power': 81, 'left_power': -1, 'right_power': -1, 'torque': 3.44505033557047, 'angular_velocity': 23.092251657330152, 'cadence': 16}}
```

**Comment by tuna-f1sh** [comment]
Yes it's a bug - the reference is passed to the closure so they all have the last one in the iteration. I've passed the value with the closure args, which should fix it. Please can you test https://github.com/Tigge/openant/compare/closure-bug

**Comment by ngolf** [comment]
Tested, Issue seems fixed.
