### ISSUE TITLE
Fails to run the example antfs_list.py

### ISSUE THREAD

**Issue by gmagno** [Tigge/openant#15]
Running the example "antfs_list.py", it fails with the traceback I am sending attached. I tried running against a Garmin Swim.

[traceback.txt](https://github.com/Tigge/openant/files/53169/traceback.txt)

**Comment by Tigge** [comment]
Ah yes, the call to set_time can actually throw `AntFSTimeException`, `AntFSDownloadException` and `AntFSUploadException`. I'll update this example as soon as I can. Thanks!

**Comment by Tigge** [comment]
Should be fixed now @gmagno. Thank you!

**Comment by gmagno** [comment]
Thanks! I think I found something else, I will post it in a different thread.

**Comment by Tigge** [comment]
Great! Let me know if you find any more issues.
