### ISSUE TITLE
Multiple Channel data receiving and receiving period issues

### ISSUE THREAD

**Issue by nicolabattaglino** [Tigge/openant#85]
Hi everyone, i need some help.
1) I'm using the raw_device_data.py script in the examples folder, in order to receive heart rate data from two devices (polar band H10 and garmin vivosmart 4).
I'm able to receive data from one device at a time, but i would like to receive data concurrently from the two devices.

I tried to create a second channel, specifying the two device ID in the channel.set_id() function for each channel, but i receive the two data alternatively, for a few seconds from the polar band and then for a few seconds from the garmin.
What's wrong with my solution? 

2) I have some doubt about the receiving period. I read in the ant+ protocol documentation the formula to calculate the channel period value depending on the needed frequency: 
channel_period_val = 32768/MessageRate(Hz)
If i want a frequency of 4Hz, i should use 8192 as channel period, and receive data every 0.25 seconds. But actually i receive the data every 3/4 seconds with this value. What I'm missing?

3) In the heart_beat.py example I would like to change the period, but I did't find how to do it. Any suggestion?

Thanks for the help.

```
from openant.easy.node import Node
from openant.easy.channel import Channel
import datetime

NETWORK_KEY = [0xB9, 0xA5, 0x21, 0xFB, 0xBD, 0x72, 0xC3, 0x45]


def on_data(data):
    page = data[0]
    if len(data) > 8:
            device_id = data[9] + (data[10] << 8)
            device_type = data[11]
            trans_type = data[12]
    if (page & 0x0F) <= 7:
        heartrate = data[7]
        print(f"on data - device id: {device_id} - heart rate: {heartrate} BPM - time: {datetime.datetime.now()}")
        
    #print(f"on_data: {data}")



def main():
    # uncomment to show verbose module logging
    # import logging
    # logging.basicConfig(level=logging.DEBUG)

    # create the network node with key
    node = Node()
    node.set_network_key(0x00, NETWORK_KEY)
    #node1 = Node()
    #node1.set_network_key(0x00, NETWORK_KEY)
    
    # create channel
    channel = node.new_channel(Channel.Type.BIDIRECTIONAL_RECEIVE)
    channel1 = node.new_channel(Channel.Type.BIDIRECTIONAL_RECEIVE)

    # setup callbacks
    channel.on_broadcast_data = on_data
    channel.on_burst_data = on_data
#
    channel1.on_broadcast_data = on_data
    channel1.on_burst_data = on_data
    ## setup slave channel
    channel.set_period(80) #8070
    channel.set_search_timeout(12)
    channel.set_rf_freq(57)
    channel.set_id(YYYYY, 120, 0)
    channel.enable_extended_messages(1)

    channel1.set_period(80) #8070
    channel1.set_search_timeout(12)
    channel1.set_rf_freq(57)
    channel1.set_id(XXXXX, 120, 0)
    channel1.enable_extended_messages(1)
    
    try:
        channel1.open()
        channel.open()
        node.start()
    finally:
        node.stop()


if __name__ == "__main__":
    main()

```

**Comment by tuna-f1sh** [comment]
The channel period is defined by the ANT+ device profile and the slave (your computer) has to be a factor of that period count. One can't change it to get a custom period. Basically, the different profiles use slightly different count values to interlace and share the radio.

Hence the period defined in https://github.com/Tigge/openant/blob/master/examples/raw_device_data.py is not a coincidence, and why it's used internally and an abstraction in https://github.com/Tigge/openant/blob/master/openant/devices/heart_rate.py: 8070 (~4 Hz). One can tune the slave to:

• 8070 counts (4.06 Hz, 4 messages/second) 
• 16140 counts (2.03 Hz, 2 messages/second) 
• 32280 counts (1.02 Hz, 1 message/second)

But not faster. So I think this is an issue with ANT+ understanding rather than a code issue.

**Comment by nicolabattaglino** [comment]
Thank you for the answer. Now I got the point.
I have one more doubt.
When trying to receive from one device only, using the https://github.com/Tigge/openant/blob/master/openant/examples/heart_rate.py script, I receive only one message every 3 seconds. It sounds weird since the default message period should be set to 8070, and therefore receive 4 messages/second. 
It doesn't happen in the https://github.com/Tigge/openant/blob/master/examples/raw_device_data.py script: setting the period to 8070, I receive 4 messages/second.
Is there something I'm not considering in the "heart_rate.py" script?

Thanks for your help!
